# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_evangelista_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evangelista',
            name='foto_perfil',
            field=models.ImageField(default='foto_perfil/evg_avatar.jpg', upload_to='foto_perfil/'),
        ),
    ]
