# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evangelista',
            name='funcao',
        ),
        migrations.RemoveField(
            model_name='evangelista',
            name='projeto',
        ),
        migrations.AlterField(
            model_name='igreja',
            name='nome',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='Evangelista',
        ),
        migrations.DeleteModel(
            name='Funcao',
        ),
        migrations.DeleteModel(
            name='Projeto',
        ),
    ]
