# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_auto_20170827_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='igreja',
            name='sede_bloco',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='igreja',
            name='sede_regional',
            field=models.BooleanField(default=False),
        ),
    ]
