# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_igreja_sede_estadual'),
    ]

    operations = [
        migrations.AddField(
            model_name='evangelista',
            name='inativo',
            field=models.BooleanField(default=False),
        ),
    ]
