# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_evangelista_inativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='evangelista',
            name='data_batismo_no_espirito_santo',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='evangelista',
            name='obreiro',
            field=models.BooleanField(default=False),
        ),
    ]
