# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 10:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_auto_20170906_0732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evangelista',
            name='data_batismo_no_espirito_santo',
        ),
    ]
