# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_evangelista_data_batismo_no_espirito_santo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evangelista',
            name='foto_perfil',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
