# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0007_auto_20170920_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='evangelista',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evangelista',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='evangelista',
            name='foto_perfil',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=b'', width_field='width_field'),
        ),
    ]
